### ISSUE TITLE
Listen

### ISSUE THREAD

**Issue by singularityhacker** [ken333135/bankless-website#16]

**Comment by ken333135** [comment]
left with 1 podcast css. created as separate issue

**Comment by singularityhacker** [comment]
Main links are clear. Use personalty links from Twitter. Default to Notion page if you cant find it.

**Comment by ken333135** [comment]
![image](https://user-images.githubusercontent.com/25942104/162220747-fa5a1d8c-b1d2-4dbb-8e19-f70e262e9d33.png)
pending: twitter links for 'ComeBackKid' and 'Lion917' .
i have no idea who they are ><

**Comment by ken333135** [comment]
left with twitter for ComeBackKid
