### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by singularityhacker** [ken333135/bankless-website#6]

**Comment by ken333135** [comment]
pending links and gifs on hompage.
created separate issues for those

**Comment by singularityhacker** [comment]
Whitepaper link @singularityhacker

**Comment by singularityhacker** [comment]
The Homepage 4 block:

1.  Projects
2.  Guilds
3.  Governance
4.  Coming soon (no link)

**Comment by singularityhacker** [comment]
Trust you guys for the chosen imagery. Designers, please help. \<--

**Comment by singularityhacker** [comment]
Buy button: Link to Uniswap with Bank preselected. 

Legal assessment: Link to paper from legal guild

@singularityhacker get these links

**Comment by singularityhacker** [comment]
Confirm multisig signers, their pfp's, and Twitter handles. 

The same goes for grants committee members.

**Comment by singularityhacker** [comment]
We don't have native signup right now. Lets allow substack signup either with widget or API: https://support.substack.com/hc/en-us/articles/360041759232-Can-I-embed-a-signup-form-for-my-publication-

**Comment by singularityhacker** [comment]
Link the footer links.

**Comment by ken333135** [comment]
items left:
1. BANK token legal assessment
2. multi sig pfp + twitter
3. grants commitee pfp + twitter
4. 2 icons in the footer

**Comment by singularityhacker** [comment]
Bankless DAO whitepaper: [https://forum.bankless.community/t/banklessdao-white-paper/3130](https://forum.bankless.community/t/banklessdao-white-paper/3130)

**Comment by singularityhacker** [comment]
Grants Committee members:

1.  Kouros = https://twitter.com/davidcoleto
2.  Grendel = https://twitter.com/GrendelMarco
3.  Icedcool = https://twitter.com/icedcool_eth
4.  Chuck = https://twitter.com/mr_cgc
5.  montgomery#8177 = https://twitter.com/WPMonty
6.  lion917#3637 = https://twitter.com/lion917_eth
7.  links#7868 = https://twitter.com/almithani

**Comment by singularityhacker** [comment]
Treasury Multisig Signers

1.  Kouros = https://twitter.com/DavidColeto
2.  0xLucas = [https://twitter.com/0x_Lucas](https://twitter.com/0x_Lucas)
3.  Above Average Joe = https://twitter.com/Abv_Avg_Joe
4.  Grendel = https://twitter.com/GrendelMarco
5.  Frog = https://twitter.com/frogmonkee
6.  Icedcool = https://twitter.com/icedcool_eth
7.  Redvan = https://mobile.twitter.com/0xredvan

**Comment by singularityhacker** [comment]
David Hoffman: ![](https://user-images.githubusercontent.com/1808235/162760171-67728ddf-584a-4beb-ac4b-c8afcc895ec5.jpg)

Ryan Sean Adams: ![](https://user-images.githubusercontent.com/1808235/162760208-44fc6013-b943-4f6e-b94b-13cad20c8ed7.jpg)

**Comment by singularityhacker** [comment]
I have asked for the signup widget.

**Comment by singularityhacker** [comment]
Bugs on the homepage (on mobile):

*   No text shoes for blocks: https://i.imgur.com/lkGZ3xl.png
*   Huge gap after blocks: https://i.imgur.com/uS7wDAR.png

**Comment by singularityhacker** [comment]
Bank token legal assessment: https://drive.google.com/file/d/1WomKnCAaQTcNGh-VhPHKe-yUiyzXgSih/view

**Comment by singularityhacker** [comment]
The newsletter subscribe widget: 

\<iframe src="https://banklessdao.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no">\</iframe>

**Comment by ken333135** [comment]
homepage done.
just need to check that the substack iframe actually triggers a signup action on substack?
